baseURL = 'https://jeff.glass'
languageCode = 'en-us'
title = 'Jeff Glass'
relativeURLs = true
paginate = 10
summaryLength = 10
enableRobotsTXT = true
googleAnalytics = 'G-BZTF8S6M1E'
[taxonomies]
  category = 'categories'
  tag = 'tags'
  one-off-tag = 'oneofftags'
[markup.highlight]
  linenos = true
  style = 'monokai'
[params]
  description = "Electronics, Making, Software Development, and Amateur Radio from a Midwest Nerd"
[markup.goldmark.renderer]
  unsafe= true