baseURL = 'https://jeff.glass'
languageCode = 'en-us'
title = 'Jeff Glass'
relativeURLs = true
paginate = 10
summaryLength = 10
[taxonomies]
  category = 'categories'
  tag = 'tags'
  one-off-tag = 'oneofftags'
[markup.highlight]
  linenos = true
  style = 'monokai'